@extends('layouts.plantilla')[cite: 7]
@section('content')[cite: 7]
    <h1 class="text-3xl font-bold">[cite: 7]
        ¡Bienvenido, {{ Auth::user()->name }}![cite: 7]
    </h1>[cite: 7]
    <p class="text-gray-600 mt-2">Panel de control de EjemploSeg</p>[cite: 7]

    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">[cite: 7]
        <div class="bg-white rounded-lg shadow-md p-6 border-l-4 border-blue-500">[cite: 7]
            <p class="text-gray-500 text-sm">Total de Personas</p>[cite: 7]
            <p class="text-3xl font-bold mt-2">{{ $totalPersonas }}</p>[cite: 7]
        </div>[cite: 7]

        {{-- Mismo patrón de tarjeta para "Intereses" --}}[cite: 7]
        {{-- (border-green-500) y "Usuarios" (border-purple-500) --}}[cite: 7]
    </div>[cite: 7]
@endsection[cite: 7]