@extends('layouts.plantilla')[cite: 6]
@section('content')[cite: 6]
    <table class="min-w-full bg-white border">[cite: 6]
        <thead>[cite: 6]
            <tr class="bg-gray-100 uppercase text-sm">[cite: 6]
                <th>ID</th><th>Nombre</th><th>Email</th><th>Registro</th>[cite: 6]
            </tr>[cite: 6]
        </thead>[cite: 6]
        <tbody>[cite: 6]
            @foreach($usuarios as $usuario)[cite: 6]
                <tr class="border-b hover:bg-gray-50">[cite: 6]
                    <td>{{ $usuario->id }}</td>[cite: 6]
                    <td>{{ $usuario->name }}</td>[cite: 6]
                    <td>{{ $usuario->email }}</td>[cite: 6]
                    <td>{{ $usuario->created_at->format('d/m/Y H:i') }}</td>[cite: 6]
                </tr>[cite: 6]
            @endforeach[cite: 6]
        </tbody>[cite: 6]
    </table>[cite: 6]
@endsection[cite: 6]